STATIONS = {
    1: "Vastral Gam",
    2: "Nirant Cross Road",
    3: "Vastral",
    4: "Rabari Colony",
    5: "Amraivadi",
    6: "Apparel Park",
    7: "Kankaria East",
    8: "Kalupur Metro Station",
    9: "Gheekanta",
    10: "Shahpur",
    11: "Old High Court",
    12: "SP Stadium",
    13: "Commerce Six Road",
    14: "Gujarat University",
    15: "Gurukul Road",
    16: "Doordarshan Kendra",
    17: "Thaltej",
    18: "Thaltej Gam",
    19: "APMC",
    20: "Jivraj Park",
    21: "Rajivnagar",
    22: "Shreyas",
    23: "Paldi",
    24: "Gandhigram",
    25: "Usmanpura",
    26: "Vijaynagar",
    27: "Vadaj",
    28: "Ranip",
    29: "Sabarmati Railway Station",
    30: "AEC",
    31: "Sabarmati",
    32: "Motera Stadium",
    33: "Koteshwar Road",
    34: "Vishwakarma College",
    35: "Tapovan Circle",
    36: "Narmada Canal",
    37: "Koba Circle",
    38: "Juna Koba",
    39: "Koba Gam",
    40: "GNLU",
    41: "Raysan",
    42: "Randesan",
    43: "Dholakuva Circle",
    44: "Infocity",
    45: "Sector-1",
    46: "Sector 10A",
    47: "Sachivalaya",
    48: "Akshardham",
    49: "Juna Sachivalaya",
    50: "Sector-16",
    51: "Sector-24",
    52: "Mahatama Mandir",
    53: "PDEU",
    54: "Gift City"
}

BASE_URL = "https://www.gujaratmetrorail.com/ahmedabad/route-and-fares/?frm_stn={frm}&to_stn={to}"
